"""
SecureVOTE 3.2 — Verifiable Threshold Cryptography Package.

Exposes DKG protocol engines, verifiable secret sharing, artifact serialization,
and threshold exception types.
"""

from app.crypto.threshold.dkg import (
    DKGComplaint,
    DKGPublicManifest,
    FeldmanRevealPackage,
    PEDERSEN_H,
    PedersenCommitmentPackage,
    PrivateSharePackage,
    SchnorrRepresentationProof,
    TrusteeDKGSession,
    TrusteePrivateKeyShare,
    build_dkg_manifest,
    derive_pedersen_h,
    prove_schnorr_representation,
    resolve_qualified_set,
    verify_complaint,
    verify_dkg_manifest,
    verify_pedersen_package,
)
from app.crypto.threshold.serialization import (
    deserialize_complaint,
    deserialize_dkg_manifest,
    deserialize_feldman_package,
    deserialize_partial_decryption_proof,
    deserialize_partial_decryption_share,
    deserialize_pedersen_package,
    deserialize_schnorr_proof,
    deserialize_share_package,
    deserialize_tally_partial_decryption_package,
    deserialize_threshold_tally_result,
    deserialize_trustee_private_key_share,
    serialize_complaint,
    serialize_dkg_manifest,
    serialize_feldman_package,
    serialize_partial_decryption_proof,
    serialize_partial_decryption_share,
    serialize_pedersen_package,
    serialize_schnorr_proof,
    serialize_share_package,
    serialize_tally_partial_decryption_package,
    serialize_threshold_tally_result,
    serialize_trustee_private_key_share,
)
from app.crypto.threshold.decryption import (
    PartialDecryptionShare,
    TallyPartialDecryptionPackage,
    compute_partial_decryption,
    compute_tally_partial_decryptions,
    verify_partial_decryption_share,
    verify_tally_partial_decryption_package,
)
from app.crypto.threshold.exceptions import (
    CommitmentVerificationError,
    ComplaintError,
    DisqualificationError,
    DKGError,
    InsufficientQualifiedTrusteesError,
    InvalidShareError,
    InvalidTrusteeSubsetError,
    PartialDecryptionProofError,
    SchnorrProofError,
    ShareVerificationError,
    TallyReconciliationError,
    ThresholdDecryptionError,
    ThresholdError,
    ThresholdSerializationError,
    ThresholdTallyError,
)
from app.crypto.threshold.proof import (
    ChaumPedersenEqualityProof,
    PartialDecryptionProof,
    check_partial_decryption_proof,
    prove_partial_decryption,
    verify_partial_decryption_proof,
)
from app.crypto.threshold.tally import (
    ThresholdTallyResult,
    ThresholdTallyVerifier,
    combine_candidate_partial_decryptions,
    compute_lagrange_coefficient,
    reconstruct_threshold_tally,
    validate_partial_share_contribution,
)



__all__ = [
    # DKG & VSS Core
    "PEDERSEN_H",
    "derive_pedersen_h",
    "SchnorrRepresentationProof",
    "prove_schnorr_representation",
    "verify_schnorr_representation",
    "PedersenCommitmentPackage",
    "PrivateSharePackage",
    "DKGComplaint",
    "FeldmanRevealPackage",
    "TrusteePrivateKeyShare",
    "DKGPublicManifest",
    "TrusteeDKGSession",
    "verify_pedersen_package",
    "verify_complaint",
    "resolve_qualified_set",
    "build_dkg_manifest",
    "verify_dkg_manifest",
    # Exceptions
    "ThresholdError",
    "DKGError",
    "CommitmentVerificationError",
    "ShareVerificationError",
    "SchnorrProofError",
    "ComplaintError",
    "DisqualificationError",
    "InsufficientQualifiedTrusteesError",
    "ThresholdSerializationError",
    "ThresholdDecryptionError",
    "PartialDecryptionProofError",
    "InvalidShareError",
    "ThresholdTallyError",
    "TallyReconciliationError",
    "InvalidTrusteeSubsetError",
    # Partial Decryption Proofs & Protocol
    "ChaumPedersenEqualityProof",
    "PartialDecryptionProof",
    "prove_partial_decryption",
    "verify_partial_decryption_proof",
    "check_partial_decryption_proof",
    "PartialDecryptionShare",
    "TallyPartialDecryptionPackage",
    "compute_partial_decryption",
    "verify_partial_decryption_share",
    "compute_tally_partial_decryptions",
    "verify_tally_partial_decryption_package",
    # Threshold Tally Combination
    "ThresholdTallyResult",
    "ThresholdTallyVerifier",
    "compute_lagrange_coefficient",
    "validate_partial_share_contribution",
    "combine_candidate_partial_decryptions",
    "reconstruct_threshold_tally",
    # Serialization
    "serialize_schnorr_proof",
    "deserialize_schnorr_proof",
    "serialize_pedersen_package",
    "deserialize_pedersen_package",
    "serialize_share_package",
    "deserialize_share_package",
    "serialize_complaint",
    "deserialize_complaint",
    "serialize_feldman_package",
    "deserialize_feldman_package",
    "serialize_dkg_manifest",
    "deserialize_dkg_manifest",
    "serialize_trustee_private_key_share",
    "deserialize_trustee_private_key_share",
    "serialize_partial_decryption_proof",
    "deserialize_partial_decryption_proof",
    "serialize_partial_decryption_share",
    "deserialize_partial_decryption_share",
    "serialize_tally_partial_decryption_package",
    "deserialize_tally_partial_decryption_package",
    "serialize_threshold_tally_result",
    "deserialize_threshold_tally_result",
]
