"""
SecureVOTE 3.2 — Verifiable Threshold Cryptography Package.

Exposes DKG protocol engines, verifiable secret sharing, artifact serialization,
and threshold exception types.
"""

from app.crypto.threshold.dkg import (
    DKGComplaint,
    DKGPublicManifest,
    FeldmanRevealPackage,
    PEDERSEN_H,
    PedersenCommitmentPackage,
    PrivateSharePackage,
    SchnorrRepresentationProof,
    TrusteeDKGSession,
    TrusteePrivateKeyShare,
    build_dkg_manifest,
    derive_pedersen_h,
    prove_schnorr_representation,
    resolve_qualified_set,
    verify_complaint,
    verify_dkg_manifest,
    verify_pedersen_package,
    verify_schnorr_representation,
)
from app.crypto.threshold.exceptions import (
    CommitmentVerificationError,
    ComplaintError,
    DisqualificationError,
    DKGError,
    InsufficientQualifiedTrusteesError,
    SchnorrProofError,
    ShareVerificationError,
    ThresholdError,
    ThresholdSerializationError,
)
from app.crypto.threshold.serialization import (
    deserialize_complaint,
    deserialize_dkg_manifest,
    deserialize_feldman_package,
    deserialize_pedersen_package,
    deserialize_schnorr_proof,
    deserialize_share_package,
    deserialize_trustee_private_key_share,
    serialize_complaint,
    serialize_dkg_manifest,
    serialize_feldman_package,
    serialize_pedersen_package,
    serialize_schnorr_proof,
    serialize_share_package,
    serialize_trustee_private_key_share,
)

__all__ = [
    # DKG & VSS Core
    "PEDERSEN_H",
    "derive_pedersen_h",
    "SchnorrRepresentationProof",
    "prove_schnorr_representation",
    "verify_schnorr_representation",
    "PedersenCommitmentPackage",
    "PrivateSharePackage",
    "DKGComplaint",
    "FeldmanRevealPackage",
    "TrusteePrivateKeyShare",
    "DKGPublicManifest",
    "TrusteeDKGSession",
    "verify_pedersen_package",
    "verify_complaint",
    "resolve_qualified_set",
    "build_dkg_manifest",
    "verify_dkg_manifest",
    # Exceptions
    "ThresholdError",
    "DKGError",
    "CommitmentVerificationError",
    "ShareVerificationError",
    "SchnorrProofError",
    "ComplaintError",
    "DisqualificationError",
    "InsufficientQualifiedTrusteesError",
    "ThresholdSerializationError",
    # Serialization
    "serialize_schnorr_proof",
    "deserialize_schnorr_proof",
    "serialize_pedersen_package",
    "deserialize_pedersen_package",
    "serialize_share_package",
    "deserialize_share_package",
    "serialize_complaint",
    "deserialize_complaint",
    "serialize_feldman_package",
    "deserialize_feldman_package",
    "serialize_dkg_manifest",
    "deserialize_dkg_manifest",
    "serialize_trustee_private_key_share",
    "deserialize_trustee_private_key_share",
]
